apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
spec:
  clusterIp: None
  selector: 
    project: expense
    module: mysql
    environment: dev
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: expense
spec:
  selector: 
    project: expense
    module: mysql
    environment: dev
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
        project: expense
        module: mysql
        environment: dev
  serviceName: "nginx"
  replicas: 2 
  template:
    metadata:
      labels:
        project: expense
        module: mysql
        environment: dev
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: sankarjuvva/mysql:latest
        volumeMounts:
        - name: mysql
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "expense-ebs"
      resources:
        requests:
          storage: 1Gi
